import { getLocale, t } from '../i18n/index.js';
import { OUTLINE_CSS } from './helpers.js';

export interface BundleParams {
  /** Document title (filename without extension) */
  title: string;
  /** Inner HTML of #docContent — already rendered (mermaid SVG, KaTeX, highlighted code) */
  content: string;
  /** CSS text strings to inline (<style> blocks already collected from frontend) */
  styles: string[];
  /** Base64-encoded images: url → data URI map */
  images: Array<{ url: string; base64: string }>;
  /** Theme identifier: 'light' or 'dark' */
  theme: 'light' | 'dark';
}

/**
 * Build a self-contained HTML document from rendered preview content.
 * All styles are inlined, local images are base64-encoded.
 * Includes an outline sidebar built from h1-h3 headings in the content.
 * Returns a complete <!DOCTYPE html> string.
 */
export function bundleHTML(params: BundleParams): string {
  const { title, content, styles, images, theme } = params;

  // 1. Replace local image src with base64 data URIs
  let html = content;
  for (const img of images) {
    html = html.replaceAll(`src="${img.url}"`, `src="${img.base64}"`);
  }

  // 2. Remove interactive elements (code copy buttons, etc.)
  html = html.replace(/<button class="code-copy-btn[^>]*><\/button>/g, '');

  // 3. Merge all CSS into one block
  const mergedCSS = styles.join('\n');

  const outlineTitle = escapeHTML(t('web.sharePage.outline'));
  const outlineToggleLabel = escapeHTML(t('web.sharePage.outlineToggle'));

  // 4. Build the full document.
  //    class="dark" keeps Tailwind `dark:` variants working in the export
  //    (the app uses darkMode:'class'), and matches `html.dark{...}` rules
  //    from the collected app styles.
  return `<!DOCTYPE html>
<html lang="${getLocale()}"${theme === 'dark' ? ' class="dark"' : ''} data-theme="${theme}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Doc77">
<title>${escapeHTML(title)}</title>
<style>
/* === Reset === */
*,*::before,*::after{box-sizing:border-box}
body{margin:0}

/* === Theme === */
:root{--bg-body:#f8fafc;--bg-card:#ffffff;--bg-code:#f1f5f9;--text-primary:#1e293b;--text-secondary:#64748b;--text-muted:#94a3b8;--border-light:#e2e8f0;--border-medium:#cbd5e1;--accent:#6366f1}
html[data-theme="dark"]{--bg-body:#0f172a;--bg-card:#1e293b;--bg-code:#1e293b;--text-primary:#e2e8f0;--text-secondary:#94a3b8;--text-muted:#64748b;--border-light:#334155;--border-medium:#475569;--accent:#818cf8}

/* === Smooth scroll === */
html{scroll-behavior:smooth}

/* === Outline styles === */
${OUTLINE_CSS}

/* === Content === */
${mergedCSS}

/* === Doc77 export chrome — placed last so it wins over collected app CSS === */
html,body{overflow:auto!important;height:auto!important}
html{background:var(--bg-body)!important}
body.doc77-export{
  background:var(--bg-body)!important;
  color:var(--text-primary)!important;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;
  line-height:1.6;
  padding:0!important;
  min-height:100vh;
}
@media print{html{background:#fff!important}body.doc77-export{background:#fff!important}footer{display:none}.doc77-outline,.doc77-outline-toggle,.doc77-outline-overlay,.doc77-outline-drawer{display:none!important}}
</style>
</head>
<body class="doc77-export">
<div class="doc77-layout">
  <div class="doc77-main">
    <article class="doc-content">${html}</article>
  </div>
  <aside class="doc77-outline" id="outlineAside">
    <div class="doc77-outline-inner">
      <div class="doc77-outline-title">${outlineTitle}</div>
      <nav class="doc77-outline-list" id="outlineList"></nav>
    </div>
  </aside>
</div>
<!-- Mobile outline FAB + drawer -->
<button class="doc77-outline-toggle" id="outlineToggle" aria-label="${outlineToggleLabel}" title="${outlineToggleLabel}">📑</button>
<div class="doc77-outline-overlay" id="outlineOverlay"></div>
<div class="doc77-outline-drawer" id="outlineDrawer">
  <div class="doc77-outline-title">${outlineTitle}</div>
  <nav class="doc77-outline-list" id="outlineDrawerList"></nav>
</div>
<footer style="text-align:center;padding:1.5rem;font-size:.75rem;color:var(--text-muted);border-top:1px solid var(--border-light);margin-top:2rem">
  Generated by <a href="https://github.com/xyy277/doc77" style="color:var(--accent)">Doc77</a>
</footer>
<script>
(function(){
  function escHtml(s){var d=document.createElement('div');d.textContent=s||'';return d.innerHTML}
  function buildOutline(){
    var container=document.querySelector('.doc-content');
    if(!container) return;
    var headings=container.querySelectorAll('h1, h2, h3');
    var aside=document.getElementById('outlineAside');
    var toggle=document.getElementById('outlineToggle');
    if(!headings.length){
      if(aside) aside.style.display='none';
      if(toggle) toggle.style.display='none';
      return;
    }
    var items=[];
    headings.forEach(function(h,i){
      if(!h.id) h.id='outline-'+i;
      var level=parseInt(h.tagName[1]);
      var indent=(level-1)*14;
      var dotColor=level===1?'var(--accent)':level===2?'var(--text-secondary)':'var(--text-muted)';
      var fw=level===1?'font-weight:600;':'';
      items.push('<a class="doc77-outline-item" href="#'+h.id+'" data-level="'+level+'" style="padding-left:'+(indent+8)+'px;'+fw+'">'+
        '<span class="doc77-outline-dot" style="background:'+dotColor+'"></span>'+
        '<span>'+escHtml(h.textContent)+'</span></a>');
    });
    var html=items.join('');
    var dl=document.getElementById('outlineList');
    var dr=document.getElementById('outlineDrawerList');
    if(dl) dl.innerHTML=html;
    if(dr) dr.innerHTML=html;
  }
  function closeDrawer(){
    document.getElementById('outlineDrawer').classList.remove('open');
    document.getElementById('outlineOverlay').style.display='none';
  }
  function openDrawer(){
    document.getElementById('outlineDrawer').classList.add('open');
    document.getElementById('outlineOverlay').style.display='block';
  }
  // Mobile toggle
  document.getElementById('outlineToggle').addEventListener('click',openDrawer);
  document.getElementById('outlineOverlay').addEventListener('click',closeDrawer);
  // Click outline item → scroll + close drawer
  document.getElementById('outlineDrawer').addEventListener('click',function(e){
    var a=e.target.closest('a');if(!a)return;
    e.preventDefault();
    var el=document.getElementById(a.getAttribute('href').slice(1));
    if(el) el.scrollIntoView({behavior:'smooth',block:'start'});
    closeDrawer();
  });
  document.getElementById('outlineList').addEventListener('click',function(e){
    var a=e.target.closest('a');if(!a)return;
    e.preventDefault();
    var el=document.getElementById(a.getAttribute('href').slice(1));
    if(el) el.scrollIntoView({behavior:'smooth',block:'start'});
  });
  // Build outline on load (content is already in the DOM)
  buildOutline();
})();
</script>
</body>
</html>`;
}

function escapeHTML(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
