import { getLocale } from '../i18n/index.js';

export interface BundleParams {
  /** Document title (filename without extension) */
  title: string;
  /** Inner HTML of #docContent — already rendered (mermaid SVG, KaTeX, highlighted code) */
  content: string;
  /** CSS text strings to inline (<style> blocks already collected from frontend) */
  styles: string[];
  /** Base64-encoded images: url → data URI map */
  images: Array<{ url: string; base64: string }>;
  /** Theme identifier: 'light' or 'dark' */
  theme: 'light' | 'dark';
}

/**
 * Build a self-contained HTML document from rendered preview content.
 * All styles are inlined, local images are base64-encoded.
 * Returns a complete <!DOCTYPE html> string.
 */
export function bundleHTML(params: BundleParams): string {
  const { title, content, styles, images, theme } = params;

  // 1. Replace local image src with base64 data URIs
  let html = content;
  for (const img of images) {
    html = html.replaceAll(`src="${img.url}"`, `src="${img.base64}"`);
  }

  // 2. Remove interactive elements (code copy buttons, etc.)
  html = html.replace(/<button class="code-copy-btn[^>]*><\/button>/g, '');

  // 3. Merge all CSS into one block
  const mergedCSS = styles.join('\n');

  // 4. Build the full document.
  //    class="dark" keeps Tailwind `dark:` variants working in the export
  //    (the app uses darkMode:'class'), and matches `html.dark{...}` rules
  //    from the collected app styles.
  return `<!DOCTYPE html>
<html lang="${getLocale()}"${theme === 'dark' ? ' class="dark"' : ''} data-theme="${theme}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Doc77">
<title>${escapeHTML(title)}</title>
<style>
/* === Reset === */
*,*::before,*::after{box-sizing:border-box}
body{margin:0}

/* === Theme === */
:root{--bg-body:#f8fafc;--bg-card:#ffffff;--bg-code:#f1f5f9;--text-primary:#1e293b;--text-secondary:#64748b;--text-muted:#94a3b8;--border-light:#e2e8f0;--border-medium:#cbd5e1;--accent:#6366f1}
html[data-theme="dark"]{--bg-body:#0f172a;--bg-card:#1e293b;--bg-code:#1e293b;--text-primary:#e2e8f0;--text-secondary:#94a3b8;--text-muted:#64748b;--border-light:#334155;--border-medium:#475569;--accent:#818cf8}

/* === Content === */
${mergedCSS}

/* === Doc77 export chrome — placed last so it wins over collected app CSS === */
html,body{overflow:auto!important;height:auto!important}
html{background:var(--bg-body)!important}
body.doc77-export{
  background:var(--bg-body)!important;
  color:var(--text-primary)!important;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;
  line-height:1.6;
  max-width:56rem;
  margin:0 auto;
  padding:3rem 3.5rem!important;
  min-height:100vh;
}
@media (max-width:640px){body.doc77-export{padding:1.75rem 1.25rem!important}}
@media print{html{background:#fff!important}body.doc77-export{padding:0!important;background:#fff!important}footer{display:none}}
</style>
</head>
<body class="doc77-export">
<article class="doc-content">${html}</article>
<footer style="margin-top:3rem;padding-top:1rem;border-top:1px solid var(--border-light);text-align:center;font-size:.75rem;color:var(--text-muted)">
  Generated by <a href="https://github.com/xyy277/doc77" style="color:var(--accent)">Doc77</a>
</footer>
</body>
</html>`;
}

function escapeHTML(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
