#!/usr/bin/env node
// Sync version from root package.json to all sub-packages
var fs = require('fs');
var path = require('path');

var ROOT = path.resolve(__dirname, '..');
var rootPkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
var version = rootPkg.version;

if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error('Invalid version in root package.json:', version);
  process.exit(1);
}

var packagesDir = path.join(ROOT, 'packages');
var packages = fs.readdirSync(packagesDir).filter(function(name) {
  return fs.existsSync(path.join(packagesDir, name, 'package.json'));
});

var updated = 0;

for (var i = 0; i < packages.length; i++) {
  var name = packages[i];

  // Generate version.gen.ts
  var genPath = path.join(packagesDir, name, 'src', 'version.gen.ts');
  var genDir = path.dirname(genPath);
  if (fs.existsSync(genDir)) {
    fs.writeFileSync(genPath, '// Auto-generated by scripts/sync-version.cjs - DO NOT EDIT\nexport const VERSION = \'' + version + '\';\n');
    updated++;
  }

  // Sync sub-package package.json version
  var pkgPath = path.join(packagesDir, name, 'package.json');
  var pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  if (pkg.version !== version) {
    pkg.version = version;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    console.log('  ' + name + ': -> ' + version);
  }
}

console.log('Version synced: ' + version + ' (' + updated + ' packages)');
